git_repo_uri: https://github.com/jeffsteed/cf-mgt.git
system_domain: sys.cf.us-east-1.arity-sandbox.com
user_id: admin
password: (( vault "secret/pcfops/sandbox/cf-admin:value" ))
client_secret: (( vault "secret/pcfops/sandbox/uaa-admin:value" ))
ldap_password: (( vault "secret/pcfops/sandbox/ldap/password:value" ))
