enabled: true
ldapHost: "172.27.95.136"
ldapPort: 389
use_tls: false
bindDN: "pcf-bind@ad.cf.us-east-1.arity-sandbox.com"
userSearchBase: "OU=users,OU=Engineering,DC=ad,DC=cf,DC=us-east-1,DC=arity-sandbox,DC=com"
userNameAttribute: "sAMAccountName"
userMailAttribute: "mail"
userObjectClass: ""
groupSearchBase: "OU=groups,OU=Engineering,DC=ad,DC=cf,DC=us-east-1,DC=arity-sandbox,DC=com"
groupAttribute: "member"
origin: ldap
